name: api_service
description: API Service Package.
version: 1.0.0
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7

flutter: null
